name: dio_smart_logger
description: Structured and secure Dio logging interceptor with cURL output, performance metrics, and deep error diagnostics.
version: 0.1.2-dev.1
repository: https://github.com/omar-hanafy/dio_smart_logger
issue_tracker: https://github.com/omar-hanafy/dio_smart_logger/issues
homepage: https://github.com/omar-hanafy/dio_smart_logger
topics:
  - dio
  - logging
  - interceptor
  - debugging

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  dart_helper_utils: ^6.0.0
  dio: ^5.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
